spring:
  application:
    name: productMicroservice

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

kafka:
  bootstrap-servers: localhost:9092, localhost:9094
  acks: all
  delivery:
    timeout: 120000
  linger: 0
  request:
    timeout: 30000
  max-in-flight-request-per-connection: 5
  transaction-id-prefix: product-service-

server:
  port: 8100

logging:
  level:
    org:
      springframework:
        kafka:
          transaction:
            KafkaTransactionManager: DEBUG
        orm:
          jpa:
            JpaTransactionManager: DEBUG
      apache:
        kafka:
          clients:
            producer:
              internals:
                TransactionManager: DEBUG
