spring:
  application:
    name: productMicroservice

kafka:
  bootstrap-servers: localhost:9092, localhost:9094
  acks: all
  delivery:
    timeout: 120000
  linger: 0
  request:
    timeout: 30000
  max-in-flight-request-per-connection: 5

server:
  port: 8100
